name: "CI"
on:
  pull_request:
  push:
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          substituters = https://zeek.cachix.org https://cache.nixos.org
          trusted-public-keys = zeek.cachix.org-1:w590YE/k5sB26LSWvDCI3dccCXipBwyPenhBH2WNDWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Nix Flake Check
      run: |
        nix -Lv flake check
    - name: Build Zeek With Nix
      run: |
        nix -Lv build ./#zeek-release
        nix develop -c zeek --version
    - name: Check Zeek Plugins
      run: nix develop -c zeek -N
    - name: Check Query Script
      run: |
        nix develop -c zeek scripts/zeek-query.zeek >/dev/null 2>&1

